fn main() {
    // The admin-app is this app's frontend: Tauri embeds the built `frontendDist` (`../dist`)
    // into the binary. Fail early, with the command to run, instead of tauri-build's terser error.
    // (`cargo tauri build`/`dev` run the frontend build themselves via `beforeBuildCommand`.)
    let frontend_index = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../dist/index.html");
    if !frontend_index.exists() {
        panic!(
            "\n\nMissing {}\n\nBuild the admin-app (the frontend) first:\n  cd csdrive-webhost-tauriapp && npm install && npm run build\n\n",
            frontend_index.display()
        );
    }

    let attributes = tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "list_secondary_windows",
            "open_new_secondary_window",
            "add_secondary_window_entry",
            "reopen_secondary_window",
            "close_secondary_window",
            "suspend_secondary_window",
            "close_all_secondary_windows",
            "suspend_all_secondary_windows",
            "focus_secondary_window",
            "list_tags",
            "add_window_tag",
            "update_window_tag",
            "reorder_window_tags",
            "remove_window_tag",
            "init_window_tab",
            "update_tab_resource",
            "submit_resource_icons",
            "create_tab_group",
            "rename_tab_group",
            "add_blank_tab",
            "clone_tab",
            "activate_tab",
            "close_tab",
            "move_tab_to_group",
            "get_global_setting",
            "set_global_setting",
            "list_system_apps",
            "get_app_state",
            "set_app_state",
            "get_code_snippets",
            "get_user_folder",
            "save_to_device",
            "fs_read_dir",
            "fs_stat",
            "fs_exists",
            "fs_read_file",
            "fs_write_file",
            "fs_mkdir",
            "fs_remove",
            "fs_rename",
            "choose_save_location",
            "filen_cache_account",
            "filen_cache_set_interval",
            "filen_cache_clear",
            "filen_cache_list",
            "filen_cache_read",
            "filen_cache_write",
            "filen_cache_mkdir",
            "filen_cache_rm",
            "filen_cache_rename",
            "filen_cache_branches",
            "filen_cache_create_branch",
            "filen_cache_branch_changes",
            "filen_cache_commit_branch",
            "filen_cache_discard_branch",
            "pick_folder",
            "list_picked_roots",
            "remove_picked_root",
            "get_data_folder_info",
            "pick_and_set_custom_data_folder",
            "reset_data_folder_to_default",
            "clear_custom_data_folder_contents",
            "delete_app_data",
            "sqlite_load",
            "sqlite_close",
            "sqlite_execute",
            "sqlite_select",
            "filen_list_accounts",
            "filen_login",
            "filen_logout",
            "filen_readdir",
            "filen_stat",
            "filen_read_file",
            "filen_write_file",
            "filen_mkdir",
            "filen_rm",
            "filen_rename",
            "list_deployable_apps",
            "get_deployable_app_html",
        ]),
    );
    tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
